<script src="<?= base_url() ?>/public/assets/js/jquery-3.5.1.min.js"></script>
<script src="<?= base_url() ?>/public/assets/js/icons/feather-icon/feather.min.js"></script>
<script src="<?= base_url() ?>/public/assets/js/icons/feather-icon/feather-icon.js"></script>
<script src="<?= base_url() ?>/public/assets/js/sidebar-menu.js"></script>
<script src="<?= base_url() ?>/public/assets/js/config.js"></script>
<script src="<?= base_url() ?>/public/assets/js/bootstrap/popper.min.js"></script>
<script src="<?= base_url() ?>/public/assets/js/bootstrap/bootstrap.min.js"></script>
<script src="<?= base_url() ?>/public/assets/js/owlcarousel/owl.carousel.js"></script>
<script src="<?= base_url() ?>/public/assets/js/owlcarousel/owl-custom.js"></script>
<script src="<?= base_url() ?>/public/assets/js/landing_sticky.js"></script>
<script src="<?= base_url() ?>/public/assets/js/landing.js"></script>
<script src="<?= base_url() ?>/public/assets/js/jarallax_libs/libs.min.js"></script>
<script src="<?= base_url() ?>/public/assets/js/script.js"></script>